name: Auto Update Weekly Data

on:
  schedule:
   - cron: '*/5 * * * *'  # chạy mỗi 5 phút  # Chạy lúc 8h sáng VN (1h UTC) mỗi ngày
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 📁 Cài dependencies
        run: npm install
        working-directory: my-mern-be

      - name: 🚀 Chạy script updateData.js
         run: node services/updateData.js
        working-directory: my-mern-be
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          API_KEY: ${{ secrets.API_KEY }}
          CITY: hanoi
